build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/native-asm"
    - PLATFORMIO_PROJECT_DIR: "examples/native-bare_c"
    - PLATFORMIO_PROJECT_DIR: "examples/psp-hello-world"
    - PLATFORMIO_PROJECT_DIR: "examples/rtosal-freertos"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-hello-world"


install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: qio platform install file://.

test_script:
  - cmd: qio run -s -d %PLATFORMIO_PROJECT_DIR%

